#!/usr/bin/perl

#
# Repeats some action until there are n failed attemps, or a success.
#

use strict;
use warnings;
use Getopt::Long;

my $sleep = 0;
my $retry = 1;
my @arguments = ();

my $result = GetOptions(
        "sleep=i" => \$sleep,
        "retry=i" => \$retry) or die usage("Invalid input $!");

do
{
        $result = fire(@ARGV);
        if ($result == 0) {
          exit(0);
        }

        $retry --;
        sleep $sleep;
} while($retry);
exit(1);

sub fire {
        my $pid = fork();
        if(not defined $pid) {
                return 1;
        } elsif ($pid == 0) {
                exec @ARGV;
        } else {
                wait;
                return $?;
        }
        return 1;
}

sub usage {
        my $msg = shift @_;

        print STDERR "$msg\n";
        print STDERR "retry [--sleep time] [--retry count] -- program args...\n";
        print STDERR "Runs program with arguments args count times\n";
        print STDERR "seconds to sleep between attempts.\n";
}

