#!/usr/bin/perl

#
# Rounds fields from a stream according to rules.
#

use strict;
use warnings;
use POSIX;

use Getopt::Long;
use List::Util qw[min max];

my $step = 1;

my $result = GetOptions(
) or die usage("Invalid input: $!");

while(<>) {
  my $line = $_;
  chomp $line;
  my $num = $line;
  my $result = round($num, 1);
  print "$result\n"
}

sub round {
  my $num = shift;
  my $base = shift;

  my $mult = int($num / $base);
  my $diff = $num - ($base * $mult);
  if ($diff >= (.5 * $base)) {
      return $base * ($mult+1);
    } else {
      return $base * $mult;
    }
}

sub usage {
  my $msg = shift @_;
  print STDERR "$msg\n";
  print STDERR "round [--step n]\n";
  print STDERR "Consumes stream of the format\n";
  print STDERR "number\n..."
}
