#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long;

my $sampleSize = 10000;
my @sample = ();
my $n = 0;

my $result = GetOptions(
        "n=f"=> \$sampleSize,
) or die "Invalid Options: $!";

if (@ARGV) {
        for my $file (@ARGV) {
                open my $fd, $file or next;
                process_file($fd);
                close $fd;
        }
} else {
        process_file($STDIN);
}

sub process_file {
        my $fd = shift @_;
        while(<>) 
        {
                if ($n < $sampleSize) {
                        push @sample, $_;
                } else {
                        my $index = int(rand($n));
                        if ($index < $sampleSize) {
                                $sample[ $index ] = $_;
                        }
                }
                $n++;
        }

        for my $line (@sample) {
                print $line;
        }
}
